name: Issue 起票時に Projects (Beta) に登録
on:
  issues:
    types: [opened]

jobs:
  manage_project:
    runs-on: ubuntu-latest
    steps:
      - name: add issue to projects
        uses: actions/add-to-project@v0.1.0
        with:
          project-url: https://github.com/orgs/TryShippoOrg/projects/2
          github-token: ${{ secrets.ACCESS_ORG }}
