name: Issue 起票時に Projects (Beta) に登録
on:
  issues:
    types: [opened]

env:
  PROJECT_OWNER: "@TryShippoOrg"
  PROJECT_NUMBER: 2
  GITHUB_TOKEN: ${{ secrets.ACCESS_ORG }}

jobs:
  manage_project:
    runs-on: ubuntu-latest

    steps:
      - name: add issue to projects
        uses: monry/actions-add-issue-to-project@v1
        with:
          github-token: ${{ env.GITHUB_TOKEN  }}
          project-owner: ${{ env.PROJECT_OWNER }}
          project-number: ${{ env.PROJECT_NUMBER }}
          issue-id: ${{ context.issue.number }}

